os: osx
osx_image: xcode9.3beta # 10.13
script:
- sudo rm -rf /usr/local/Homebrew
- sudo rvm implode --force
- ./script/boxen --no-fde --stealth --no-pull --debug --profile --login $BOXEN_GITHUB_LOGIN || test $? -eq 2
- source /opt/boxen/env.sh
- bundle exec rspec spec
install: '' # empty to prevent it trying to re-bundle
env:
  global:
    - HOMEBREW_NO_AUTO_UPDATE=1
    - HOMEBREW_VERBOSE=1
