os: osx
osx_image: xcode9.2
script:
  - sudo rm -rf /usr/local/Homebrew
  - sudo rvm implode --force
  - ./script/boxen --no-fde --no-pull --debug --profile --login $BOXEN_GITHUB_LOGIN --token $BOXEN_GITHUB_PASSWORD || test $? -eq 2
  - source /opt/boxen/env.sh
  - bundle exec rspec spec
before_install:
  - cat ':ssl_verify_mode: 0' >> ~/.gemrc
  - sudo gem install -f bundler -v '~> 1.10.5'
env:
  global:
    - HOMEBREW_NO_AUTO_UPDATE=1
    - HOMEBREW_VERBOSE=1
